#!/usr/bin/env python3
"""Regenerate everything that must agree with the device table.

`src-tauri/src/devices.rs` is the single source of truth for supported
hardware. Four other places have to match it, and a contributor who adds a
device should not have to remember them:

  * packaging/70-hidra.rules   — Linux needs a udev rule per USB id
  * README.md, README.pt-BR.md — the compatibility tables
  * site/index.html            — the same table on the website

    python3 scripts/sync-devices.py            # rewrite them
    python3 scripts/sync-devices.py --check    # fail if they are stale (CI)

Adding a device is then one edit plus one command.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEVICES_RS = ROOT / "src-tauri/src/devices.rs"
RULES = ROOT / "packaging/70-hidra.rules"
README_EN = ROOT / "README.md"
README_PT = ROOT / "README.pt-BR.md"
SITE = ROOT / "site/index.html"

START, END = "<!-- devices:start -->", "<!-- devices:end -->"

# What a protocol gives the user, for the feature column. One line per protocol.
FEATURES = {
    "Compx17": {
        "en": "lighting, DPI, buttons, polling",
        "pt": "iluminação, DPI, botões, polling",
    },
    "Sonix64": {
        "en": "18 effects + per-key colour, 3 profiles, key remap",
        "pt": "18 efeitos + cor por tecla, 3 perfis, remapeamento",
    },
}

CONNECTION = {
    "Receiver": {"en": "2.4 GHz receiver", "pt": "receptor 2.4 GHz"},
    "Wired": {"en": "cable", "pt": "cabo"},
}

STATUS = {
    "Verified": {"en": "✅ verified", "pt": "✅ validado"},
    "Reported": {"en": "🟡 reported", "pt": "🟡 relatado"},
}

FIELD = r'{field}:\s*(?:"(?P<{field}_s>[^"]*)"|(?P<{field}_v>[A-Za-z0-9_:]+|0x[0-9a-fA-F]+|-?\d+))'


def parse_devices() -> list[dict]:
    text = DEVICES_RS.read_text()
    body = text[text.index("pub const SUPPORTED"):]
    devices = []
    for block in re.findall(r"Device\s*\{(.*?)\n    \}", body, re.S):
        entry = {}
        for field in (
            "vendor", "model", "vid", "pid", "kind", "protocol",
            "interface", "connection", "support",
        ):
            m = re.search(FIELD.format(field=field), block)
            if not m:
                sys.exit(f"devices.rs: an entry is missing `{field}`")
            value = m.group(f"{field}_s")
            if value is None:
                value = m.group(f"{field}_v").split("::")[-1]
            entry[field] = value
        devices.append(entry)
    if not devices:
        sys.exit("devices.rs: no Device entries found — did the table's shape change?")
    return devices


def label(device: dict, devices: list[dict], lang: str) -> str:
    """Human name for a row, disambiguating a model that has several entries."""
    name = f'{device["vendor"]} {device["model"]}'
    twins = [d for d in devices if (d["vendor"], d["model"]) == (device["vendor"], device["model"])]
    if len(twins) > 1:
        name += f' — {CONNECTION[device["connection"]][lang]}'
    return name


def render_rules(devices: list[dict]) -> str:
    lines = [
        "# HIDra — non-root access to the supported HID config interfaces (systemd-logind uaccess).",
        "#",
        "# GENERATED by scripts/sync-devices.py from src-tauri/src/devices.rs — do not edit by hand.",
        "# Copy to /etc/udev/rules.d/ and reload the rules, then replug the device.",
        "# (The .deb and .rpm packages install this for you.)",
        "",
    ]
    seen: set[tuple[str, str]] = set()
    for d in devices:
        key = (d["vid"], d["pid"])
        if key in seen:
            continue
        seen.add(key)
        vid, pid = d["vid"][2:].lower(), d["pid"][2:].lower()
        lines.append(f'# {d["vendor"]} {d["model"]} — {CONNECTION[d["connection"]]["en"]}')
        lines.append(
            f'SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{vid}", '
            f'ATTRS{{idProduct}}=="{pid}", MODE="0660", TAG+="uaccess"'
        )
    return "\n".join(lines) + "\n"


def render_markdown(devices: list[dict], lang: str) -> str:
    head = {
        "en": "| Device | USB ID | Status | Features |\n| --- | --- | --- | --- |",
        "pt": "| Dispositivo | ID USB | Situação | Recursos |\n| --- | --- | --- | --- |",
    }[lang]
    rows = [head]
    for d in devices:
        usb = f'`{d["vid"][2:].upper()}:{d["pid"][2:].upper()}`'
        features = FEATURES.get(d["protocol"], {}).get(lang, d["protocol"])
        rows.append(f'| {label(d, devices, lang)} | {usb} | {STATUS[d["support"]][lang]} | {features} |')
    return "\n".join(rows)


def render_html(devices: list[dict]) -> str:
    rows = []
    for d in devices:
        usb = f'{d["vid"][2:].upper()}:{d["pid"][2:].upper()}'
        twins = [x for x in devices if (x["vendor"], x["model"]) == (d["vendor"], d["model"])]
        suffix = ""
        if len(twins) > 1:
            suffix = (
                f' <span class="size" data-en>— {CONNECTION[d["connection"]]["en"]}</span>'
                f'<span class="size" data-pt>— {CONNECTION[d["connection"]]["pt"]}</span>'
            )
        ok = " tag--ok" if d["support"] == "Verified" else ""
        en = "verified" if d["support"] == "Verified" else "reported"
        pt = "validado" if d["support"] == "Verified" else "relatado"
        rows.append(
            "            <tr>\n"
            f'              <td>{d["vendor"]} {d["model"]}{suffix}</td>\n'
            f"              <td><code>{usb}</code></td>\n"
            f'              <td><span class="tag{ok}" data-en>{en}</span>'
            f'<span class="tag{ok}" data-pt>{pt}</span></td>\n'
            "            </tr>"
        )
    return "\n".join(rows)


def splice(path: Path, block: str) -> str:
    text = path.read_text()
    if START not in text or END not in text:
        sys.exit(f"{path}: missing {START} / {END} markers")
    before = text[: text.index(START) + len(START)]
    # Keep whatever indentation the closing marker already had.
    end = text.index(END)
    line_start = text.rfind("\n", 0, end) + 1
    after = text[line_start:]
    return f"{before}\n{block}\n{after}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only report staleness, change nothing")
    args = ap.parse_args()

    devices = parse_devices()
    wanted = {
        RULES: render_rules(devices),
        README_EN: splice(README_EN, render_markdown(devices, "en")),
        README_PT: splice(README_PT, render_markdown(devices, "pt")),
        SITE: splice(SITE, render_html(devices)),
    }

    stale = [p for p, content in wanted.items() if p.read_text() != content]
    if args.check:
        if stale:
            print("Out of date with src-tauri/src/devices.rs:", file=sys.stderr)
            for p in stale:
                print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
            print("\nRun: python3 scripts/sync-devices.py", file=sys.stderr)
            return 1
        print(f"{len(devices)} devices; every generated file is in sync.")
        return 0

    for path, content in wanted.items():
        if path in stale:
            path.write_text(content)
            print(f"updated {path.relative_to(ROOT)}")
    if not stale:
        print("already in sync")
    print(f"{len(devices)} devices in the table.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
